---
- name: Czertainly host config
  hosts: all
  connection: local

  pre_tasks:
    - name: Get czertainly versions
      ansible.builtin.command: /usr/bin/czertainly-versions
      tags: always
      changed_when: false
      register: versions
    - name: CZERTAINLY versions
      ansible.builtin.debug:
        msg: "{{ versions.stdout }}"
    - name: Check if keycloak file exists
      ansible.builtin.stat:
        path: "/etc/czertainly-ansible/vars/keycloak.yml"
      register: keycloak_result
      tags: always
    - name: Generate secret for keycloak
      ansible.builtin.set_fact:
        key_cloak_secret: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits']) }}"
      when: not keycloak_result.stat.exists
      tags: always
    - name: Write secret for keycloak
      ansible.builtin.template:
        src: "keycloak.yml.j2"
        dest: "/etc/czertainly-ansible/vars/keycloak.yml"
        mode: "0640"
      when: not keycloak_result.stat.exists
      tags: always
    - name: "Read database.yml"
      ansible.builtin.include_vars: /etc/czertainly-ansible/vars/database.yml
      tags: always
    - name: "Read docker.yml"
      ansible.builtin.include_vars: /etc/czertainly-ansible/vars/docker.yml
      tags: always
    - name: "Read proxy.yml"
      ansible.builtin.include_vars: /etc/czertainly-ansible/vars/proxy.yml
      tags: always
    - name: "Read network.yml"
      ansible.builtin.include_vars: /etc/czertainly-ansible/vars/network.yml
      tags: always
    - name: "Read ntp.yml"
      ansible.builtin.include_vars: /etc/czertainly-ansible/vars/ntp.yml
      tags: always
    - name: "Read ingress.yml"
      ansible.builtin.include_vars: /etc/czertainly-ansible/vars/ingress.yml
      tags: always
    - name: "Read trustedCA.yml"
      ansible.builtin.include_vars: /etc/czertainly-ansible/vars/trustedCA.yml
      tags: always
    - name: "Read czertainly.yml"
      ansible.builtin.include_vars: /etc/czertainly-ansible/vars/czertainly.yml
      tags: always
    - name: "Read keycloak.yml"
      ansible.builtin.include_vars: /etc/czertainly-ansible/vars/keycloak.yml
      tags: always
    - name: "Read email.yml"
      ansible.builtin.include_vars: /etc/czertainly-ansible/vars/email.yml
      tags: always

  vars:
    # Here we are preparing dict with environment which is based on
    # configuration. In most cases values of that dict will be
    # undefined, to prevent Ansible from failing we set default value
    # to ''.
    proxy_env:
      http_proxy: "{{ proxy.http | default('') }}"
      HTTP_PROXY: "{{ proxy.http | default('') }}"
      https_proxy: "{{ proxy.https | default('') }}"
      HTTPS_PROXY: "{{ proxy.https | default('') }}"
      ftp_proxy: "{{ proxy.ftp | default('') }}"
      FTP_PROXY: "{{ proxy.ftp | default('') }}"
      ftps_proxy: "{{ proxy.ftps | default('') }}"
      FTPS_PROXY: "{{ proxy.ftps | default('') }}"
      no_proxy: "{{ proxy.dont_use_for | default('') | join(',') }}"
      NO_PROXY: "{{ proxy.dont_use_for | default('') | join(',') }}"
    # by default rke2 role only install kube cfg for root
    custom_kube_cfg_dir:
      - owner: "czertainly"
        group: "czertainly"
        dir: "/home/czertainly/.kube"
    # All CZERTAINLY services are running in parallel and causing big
    # stress on DB, it is better to support more simultaneous connections.
    postgres_max_connections: 250
    # Following vars are used by systemd-timesyncd component
    ntp_servers: "{{ ntp.servers }}"
    system_timezone: "{{ ntp.timezone }}"
  # Now we filterout those dict keys which have environment valuables
  # which have value equal to ''. This and previous block is need to
  # be able to use HTTP_PROXY and fiends and without playbook/machine
  # restart. Inspiration for filter:
  # https://medium.com/opsops/how-to-filter-a-dictionary-in-ansible-b5dad74a6f66
  environment: '{{ proxy_env|dict2items|rejectattr("value", "equalto", "")|list|items2dict }}'

  roles:
    - role: network
    - role: systemd-timesyncd
      apply:
        tags:
          - ntp
      tags: ntp
      when: ntp is defined
    - role: http-proxy
    - role: postgres
    - role: helm
    - role: rke2
    - role: czertainly
