---
on:
  push:
    branches: [main, master, develop, fix-deb-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get -y install debhelper dpkg-dev build-essential

      - name: Build package
        run: ./build-deb.sh

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: czertainly-appliance-tools
          path: ${{ github.workspace }}/czertainly-appliance-tools*.deb

      - name: Publish package
        uses: mdallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: 'czertainly-appliance-tools*deb'
          remote: ${{ vars.DEB_REPO_DIRECTORY }}
          host: ${{ vars.DEB_REPO_HOST }}
          user: ${{ vars.DEB_REPO_USER }}
          key: ${{ secrets.DEB_REPO_KEY }}
          pre_upload: ls -la ${{ vars.DEB_REPO_DIRECTORY }}/*.deb && rm ${{ vars.DEB_REPO_DIRECTORY }}/*.deb; true
          post_upload: set -e ; sudo ${{ vars.DEB_REPO_MANAGER }} add ${{ github.ref_name }} `ls -1c ${{ vars.DEB_REPO_DIRECTORY }}/czertainly-appliance-tools*.deb | head -1`; echo "Finished with error code $?"
